//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by testvideochatsample.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTVIDEOCHATSAMPLE_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     134
#define IDC_VIDEOCHATCTRL1              1000
#define IDC_COMBO1                      1001
#define IDC_COMBO2                      1002
#define IDC_COMBO3                      1003
#define IDC_EDITVIDEOBITRATE            1004
#define IDC_CBOVIDEOCOMPLEX             1005
#define IDC_CBOAUDIOCOMPLEX             1006
#define IDC_CBOAUDIOQUALITY             1007
#define IDC_EDITCONNECTIP               1008
#define IDC_EDITCONNECTPORT             1009
#define IDC_EDITPORTNO                  1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_EDITCONFNO                  1011
#define IDC_EDITFRAMERATE               1012
#define IDC_EDITUSERID                  1012
#define IDC_CHECKSENDVIDEO              1013
#define IDC_CHECKSENDAUDIO              1014
#define IDC_STATICVIDEOBITRATE          1015
#define IDC_STATICAUDIOBITRATE          1016
#define IDC_CHECKRECEIVEVIDEO           1017
#define IDC_EDITLISTENIP                1018
#define IDC_EDITLISTENPORT              1019
#define IDC_CHKVMRSENDER                1019
#define IDC_CHECKRECVIDEO               1020
#define IDC_CHECKRECAUDIO               1021
#define IDC_BUTTON3                     1022
#define IDC_BUTTON4                     1023
#define IDC_VIDEOCHATCTRL2              1024
#define IDC_CHECK1                      1025
#define IDC_COMBO4                      1026
#define IDC_CBOROTATE                   1026
#define IDC_EDIT1                       1028
#define IDC_EDIT2                       1029
#define IDC_EDIT3                       1030
#define IDC_BUTTON5                     1030
#define IDC_EDIT4                       1031
#define IDC_VIDEOCHATRECEIVECTRL1       1031
#define IDC_EDIT5                       1032
#define IDC_EDIT6                       1033
#define IDC_EDT_CONF_NO                 1033
#define IDC_EDT_USER_ID                 1034
#define IDC_EDIT7                       1035
#define IDC_EDIT8                       1036
#define IDC_BTNCHANGECAPAREA            1037
#define IDC_BTNCHANGEVIRTUALFORMAT      1038
#define IDC_RADIOASPECTRATIO1           1039
#define IDC_RADIOASPECTRATIO2           1040
#define IDC_RADIOASPECTRATIO3           1041
#define IDC_CHKCAPTUREFILE              1042
#define IDC_CHKMAXFIRST                 1043
#define IDC_RADIOOUTMP4                 1044
#define IDC_RADIOOUTWMV                 1045
#define IDC_EDITMP4WIDTH                1046
#define IDC_EDITMP4HEIGHT               1047
#define IDC_EDITAUDIOCHANNEL            1048
#define IDC_EDITMP4VIDEOBITRATE         1049
#define IDC_EDITMP4AUDIOBITRATE         1050
#define IDC_EDITMP4FRAMERATE            1051
#define IDC_EDITMP4AUDIOSAMPLERATE      1052
#define IDC_BTNCURSORHIGHLIGHT          1053
#define IDC_BTNLEFTCLICKCOLOR           1054
#define IDC_BTNRIGHTCLICKCOLOR          1055
#define IDC_CHKUSESYSCURSOR             1056
#define IDC_EDITCUSTOMCURSOR            1057
#define IDC_BTNSELCUSTOMCURSOR          1058
#define IDC_EDITINDEXVIDEOWND           1059
#define IDC_BTNSNAPSHOT                 1060
#define IDC_BTNSHOWONE2ONE              1061
#define IDC_BTNCLOSEONE2ONE2            1062
#define IDC_LIST1                       1063
#define IDC_RADIOVIDEOCHATTYPE          1064
#define IDC_RADIO2                      1065
#define IDC_STATICCONNECTIP             1066
#define IDC_STATICLISTENIP              1067
#define IDC_CHKMOUSEHIGHLIGHT           1067
#define IDC_CHKINVERTCOLOR              1069
#define IDC_CHKGRAYSCALE                1070
#define IDC_EDITLIGHTR                  1071
#define IDC_EDITLIGHTG                  1072
#define IDC_EDITLIGHTB                  1073
#define IDC_BTNLIGHTNESSCHANGE          1074
#define IDC_BTNLIGHTDEFAULT             1075
#define IDC_EDITCHATMESSAGE             1077
#define IDC_BUTTONCHATMSGSEND           1078
#define IDC_CBOCHATFONT                 1079
#define IDC_CBOCHATFONTSIZE             1080
#define IDC_CBOFONTSTYLE                1081
#define IDC_CBOSTATE                    1082
#define IDC_CHKFILLBG                   1083
#define IDC_CBOCHATDIR                  1084
#define IDC_EDITFADEIN                  1085
#define IDC_EDITFADEOUT                 1086
#define IDC_BUTTONFADETIME              1088
#define IDC_EDITTEXTALPHA               1089
#define IDC_BUTTONTEXTCOLOR             1090
#define IDC_EDITBGALPHA                 1091
#define IDC_BUTTONBGCOLOR               1092
#define IDC_EDITCHATX                   1093
#define IDC_EDITCHATY                   1094
#define IDC_BUTTONCHATPOS               1095
#define IDC_EDITCHATSPEED               1096
#define IDC_BUTTONCHATSPEED             1097
#define IDC_CBOEFFECTTYPE               1098
#define IDC_EDITOVERLAYIMAGE            1099
#define IDC_BTNSELOVERLAYIMAGE          1100
#define IDC_BTNOVERLAYIMAGEDRAW         1101
#define IDC_EDITOVERLAYIMAGEALPHA       1102
#define IDC_BTNOVERLAYIMAGETRANCOLOR    1103
#define IDC_EDITOVERLAYIMAGEX           1104
#define IDC_EDITOVERLAYIMAGEY           1105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
