#if !defined(AFX_VIDEOCHAT_H__F2990966_29BA_4E59_ACB5_9B1DABD47797__INCLUDED_)
#define AFX_VIDEOCHAT_H__F2990966_29BA_4E59_ACB5_9B1DABD47797__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// Cvideochat wrapper class

class Cvideochat : public CWnd
{
protected:
	DECLARE_DYNCREATE(Cvideochat)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9da66afa, 0xf784, 0x426a, { 0x82, 0xf6, 0x7d, 0xd7, 0x54, 0xc1, 0xa0, 0x39 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetVideoFormat();
	void SetVideoFormat(short);
	CString GetVideoDeviceName();
	void SetVideoDeviceName(LPCTSTR);
	CString GetAudioDeviceName();
	void SetAudioDeviceName(LPCTSTR);
	long GetFrameRate();
	void SetFrameRate(long);
	long GetVideoBitrate();
	void SetVideoBitrate(long);
	short GetAudioQuality();
	void SetAudioQuality(short);
	BOOL GetSendVideoStream();
	void SetSendVideoStream(BOOL);
	BOOL GetSendAudioStream();
	void SetSendAudioStream(BOOL);
	short GetAudioComplexity();
	void SetAudioComplexity(short);
	CString GetLicenseKey();
	void SetLicenseKey(LPCTSTR);
	short GetVideoDevice();
	void SetVideoDevice(short);
	short GetAudioDevice();
	void SetAudioDevice(short);
	BOOL GetEchoCanceler();
	void SetEchoCanceler(BOOL);
	long GetConferenceNumber();
	void SetConferenceNumber(long);
	long GetConferenceUserID();
	void SetConferenceUserID(long);
	BOOL GetUseDefaultVMR();
	void SetUseDefaultVMR(BOOL);
	short GetOverlayType();
	void SetOverlayType(short);

// Operations
public:
	void AboutBox();
	short GetVideoDeviceCount();
	short GetAudioDeviceCount();
	CString GetVideoDeviceName(short iIndex);
	CString GetAudioDeviceName(short iIndex);
	short Connect(LPCTSTR strIPAddress, long iPortNo);
	void Disconnect();
	CString GetIPAddress();
	void VirtualScreenCaptureArea(long iLeft, long iTop, long iWidth, long iHeight);
	void VirtualScreenCaptureFullScreen(BOOL bFullScreen);
	void VirtualScreenCursorFile(LPCTSTR strCursorFile);
	void VirtualScreenHighlightColor(unsigned long clrColor);
	void VirtualScreenLeftClickColor(unsigned long clrColor);
	void VirtualScreenRightClickColor(unsigned long clrColor);
	void VirtualScreenShowSystemCursor(BOOL bShow);
	void RefreshDevice();
	void Rotate(short iRotateValue);
	void InvertColor(BOOL bInvert);
	void GrayScale(BOOL bEnable);
	void Lightness(short iR, short iG, short iB);
	void VirtualScreenShowMouseHighlight(BOOL bShow);
	void ChatBannerTextColor(short iR, short iG, short iB, short iA);
	void ChatBannerState(short iState);
	void ChatBannerSetFont(LPCTSTR strFontName, short iFontSize, short iStyle);
	void ChatBannerFadeEdge(double fFadeStart, double fFadeEnd);
	void ChatBannerFillBgColor(BOOL bFill);
	void ChatBannerPos(short iX, short iY);
	void ChatBannerDirection(short iDirection);
	void ChatBannerSpeed(short iSpeed);
	void ChatBannerBgColor(short iR, short iG, short iB, short iA);
	void ChatBannerAddText(LPCTSTR strText);
	void SetOverlayImage(LPCTSTR strImage);
	void SetOverlayImagePos(long iX, long iY);
	void SetOverlayImageTransColor(short iTransR, short iTransG, short iTransB, short iImageAlpha);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOCHAT_H__F2990966_29BA_4E59_ACB5_9B1DABD47797__INCLUDED_)
