// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "videochatserver.h"

/////////////////////////////////////////////////////////////////////////////
// CVideoChatServer

IMPLEMENT_DYNCREATE(CVideoChatServer, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CVideoChatServer properties

BOOL CVideoChatServer::GetUseRandomNumber()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CVideoChatServer::SetUseRandomNumber(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

CString CVideoChatServer::GetLicenseKey()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CVideoChatServer::SetLicenseKey(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CVideoChatServer operations

void CVideoChatServer::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CVideoChatServer::CreateConference()
{
	long result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CVideoChatServer::UnInitServer()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CVideoChatServer::AddUser(long iConfNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		iConfNumber);
	return result;
}

void CVideoChatServer::RemoveUser(long iConfNumber, long iUserID)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iConfNumber, iUserID);
}

void CVideoChatServer::InitServer(long iPortNo, long iTimeOut)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 iPortNo, iTimeOut);
}
