#if !defined(AFX_VIDEOCHATSERVER_H__5AEFD6D2_5C38_4DD6_8002_8578ECA06BF4__INCLUDED_)
#define AFX_VIDEOCHATSERVER_H__5AEFD6D2_5C38_4DD6_8002_8578ECA06BF4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVideoChatServer wrapper class

class CVideoChatServer : public CWnd
{
protected:
	DECLARE_DYNCREATE(CVideoChatServer)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd2f506e8, 0xdca3, 0x4ce7, { 0x80, 0xdd, 0x20, 0x29, 0x8, 0x4c, 0xb1, 0xb3 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetUseRandomNumber();
	void SetUseRandomNumber(BOOL);
	CString GetLicenseKey();
	void SetLicenseKey(LPCTSTR);

// Operations
public:
	void AboutBox();
	long CreateConference();
	void UnInitServer();
	long AddUser(long iConfNumber);
	void RemoveUser(long iConfNumber, long iUserID);
	void InitServer(long iPortNo, long iTimeOut);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOCHATSERVER_H__5AEFD6D2_5C38_4DD6_8002_8578ECA06BF4__INCLUDED_)
